include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"